### ISSUE TITLE
New release/tag

### ISSUE THREAD

**Issue by scribam** [Linaro/vixl#84]
Hi,

Can you create a new release/tag please? Or can I use the HEAD of the `main` branch safely?
The main feature I want to have is the compatibility fixes with MSVC added last year

**Comment by mmc28a** [comment]
Sure, I can tag a release. We've a commit soon that enables Python 3 everywhere, so do you want to wait for that?
Master is meant to work all of the time, but I understand version-tagged releases are easier to deal with than commit hashes.

**Comment by scribam** [comment]
Yes, I can wait, I am not in hurry.
Thank you :slightly_smiling_face:

**Comment by scribam** [comment]
@mmc28a I will be happy to have a new release/tag from the current main branch if that's ok with you

**Comment by mmc28a** [comment]
There's one more scripting change that's reviewed and ready to go, but needs a PR. Once that's in, I'll tag 7.0.0.

**Comment by mmc28a** [comment]
7.0.0 released. Apologies for it taking longer than expected - ran into a few test issues.
