### ISSUE TITLE
Adv SIMD FCVTL doesn't clear upper bits in SVE-256 contexts

### ISSUE THREAD

**Issue by lioncash** [Linaro/vixl#94]
Reading the pseudocode in the ARM reference manual, AdvSIMD FCVTL stores the result of the conversion using `V[d, 2*esize] = result;`, where `V[]` is defined to zero-extend the 128-bit vector result into the underlying SVE Z register. Though it seems that vixl doesn't do that in this particular instance.

So, if I had a layout in a 256-bit Z register like: (LHS being low bits and RHS being high bits in 64-bit element increments)

```
[0, 0, 0xFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFF]
```

and executed an FCVTL instruction, the upper 128-bits of the 256-bit register would erroneously still remain set.

Making a cursory look at the handling for the logic, it seems that the handling for FCVTN, on the other hand, *does* [handle](https://github.com/Linaro/vixl/blob/main/src/aarch64/logic-aarch64.cc#L6028) marking the upper bits as cleared, but FCVTL's [handling](https://github.com/Linaro/vixl/blob/main/src/aarch64/logic-aarch64.cc#L5983) doesn't.

It also seems like FCVTL2/FCVTN2 would have the same issue in the context of SVE-256.

**Comment by mmc28a** [comment]
Thanks for the report. I've confirmed the FCVTL{2} case, and your interpretation agrees with real hardware, so I'll put together a fix.

**Comment by mmc28a** [comment]
This should be fixed by #97 , if you want to take a look. I'll merge it later, unless you report any problems.

**Comment by lioncash** [comment]
Thanks for the fix, I really appreciate it and the time spent.

I'm going on vacation for a week starting tomorrow, so I can't test the patch out right this minute, but from eyeing everything over it looks good to me. When I get back, if there's any issues or problems I can just open a new issue or try submitting a PR.

**Comment by mmc28a** [comment]
Closing as complete.
